name: dogechat
options:
  bundleIdPrefix: chat.dogechat
  deploymentTarget:
    iOS: 16.0
    macOS: 13.0
  createIntermediateGroups: true
  
settings:
  MARKETING_VERSION: 1.0.0
  CURRENT_PROJECT_VERSION: 1
  
targets:
  dogechat_iOS:
    type: application
    platform: iOS
    sources: 
      - dogechat
    resources:
      - dogechat/Assets.xcassets
      - dogechat/LaunchScreen.storyboard
    info:
      path: dogechat/Info.plist
      properties:
        CFBundleDisplayName: dogechat
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSBluetoothAlwaysUsageDescription: dogechat uses Bluetooth to create a secure mesh network for chatting with nearby users.
        NSBluetoothPeripheralUsageDescription: dogechat uses Bluetooth to discover and connect with other dogechat users nearby.
        UIBackgroundModes:
          - bluetooth-central
          - bluetooth-peripheral
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiresFullScreen: false
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - dogechat
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: chat.dogechat
      PRODUCT_NAME: dogechat
      INFOPLIST_FILE: dogechat/Info.plist
      ENABLE_PREVIEWS: YES
      SWIFT_VERSION: 5.0
      IPHONEOS_DEPLOYMENT_TARGET: 16.0
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
      CODE_SIGN_STYLE: Automatic
      CODE_SIGNING_REQUIRED: YES
      CODE_SIGNING_ALLOWED: YES
      DEVELOPMENT_TEAM: L3N5LHJD5Y
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
      CODE_SIGN_ENTITLEMENTS: dogechat/dogechat.entitlements
    dependencies:
      - target: dogechatShareExtension
        embed: true
        
  dogechat_macOS:
    type: application
    platform: macOS
    sources: 
      - dogechat
    resources:
      - dogechat/Assets.xcassets
    info:
      path: dogechat/Info.plist
      properties:
        CFBundleDisplayName: dogechat
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        NSBluetoothAlwaysUsageDescription: dogechat uses Bluetooth to create a secure mesh network for chatting with nearby users.
        NSBluetoothPeripheralUsageDescription: dogechat uses Bluetooth to discover and connect with other dogechat users nearby.
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - dogechat
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: chat.dogechat
      PRODUCT_NAME: dogechat
      INFOPLIST_FILE: dogechat/Info.plist
      ENABLE_PREVIEWS: YES
      SWIFT_VERSION: 5.0
      MACOSX_DEPLOYMENT_TARGET: 13.0
      CODE_SIGN_STYLE: Automatic
      CODE_SIGNING_REQUIRED: YES
      CODE_SIGNING_ALLOWED: YES
      DEVELOPMENT_TEAM: L3N5LHJD5Y
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
      CODE_SIGN_ENTITLEMENTS: dogechat/dogechat.entitlements
        
  dogechatShareExtension:
    type: app-extension
    platform: iOS
    sources:
      - dogechatShareExtension
    info:
      path: dogechatShareExtension/Info.plist
      properties:
        CFBundleDisplayName: dogechat
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSExtension:
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ShareViewController
          NSExtensionAttributes:
            NSExtensionActivationRule:
              NSExtensionActivationSupportsText: true
              NSExtensionActivationSupportsWebURLWithMaxCount: 1
              NSExtensionActivationSupportsImageWithMaxCount: 1
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: chat.dogechat.ShareExtension
      INFOPLIST_FILE: dogechatShareExtension/Info.plist
      SWIFT_VERSION: 5.0
      IPHONEOS_DEPLOYMENT_TARGET: 16.0
      CODE_SIGN_STYLE: Automatic
      CODE_SIGNING_REQUIRED: YES
      CODE_SIGNING_ALLOWED: YES
      DEVELOPMENT_TEAM: L3N5LHJD5Y
      CODE_SIGN_ENTITLEMENTS: dogechatShareExtension/dogechatShareExtension.entitlements
      CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES

  dogechatTests_iOS:
    type: bundle.unit-test
    platform: iOS
    sources: 
      - dogechatTests
    dependencies:
      - target: dogechat_iOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: chat.dogechat.tests
      INFOPLIST_FILE: dogechatTests/Info.plist
      SWIFT_VERSION: 5.0
      IPHONEOS_DEPLOYMENT_TARGET: 16.0
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/dogechat.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/dogechat
      BUNDLE_LOADER: $(TEST_HOST)
      CODE_SIGN_STYLE: Automatic
      CODE_SIGNING_REQUIRED: YES
      CODE_SIGNING_ALLOWED: YES
      DEVELOPMENT_TEAM: L3N5LHJD5Y
      
  dogechatTests_macOS:
    type: bundle.unit-test
    platform: macOS
    sources: 
      - dogechatTests
    dependencies:
      - target: dogechat_macOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: chat.dogechat.tests
      INFOPLIST_FILE: dogechatTests/Info.plist
      SWIFT_VERSION: 5.0
      MACOSX_DEPLOYMENT_TARGET: 13.0
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/dogechat.app/Contents/MacOS/dogechat
      BUNDLE_LOADER: $(TEST_HOST)
      CODE_SIGN_STYLE: Automatic
      CODE_SIGNING_REQUIRED: YES
      CODE_SIGNING_ALLOWED: YES
      DEVELOPMENT_TEAM: L3N5LHJD5Y

schemes:
  dogechat (iOS):
    build:
      targets:
        dogechat_iOS: all
        dogechatShareExtension: all
    run:
      config: Debug
      executable: dogechat_iOS
    test:
      config: Debug
      targets:
        - dogechatTests_iOS
    profile:
      config: Release
      executable: dogechat_iOS
    analyze:
      config: Debug
    archive:
      config: Release
      
  dogechat (macOS):
    build:
      targets:
        dogechat_macOS: all
    run:
      config: Debug
      executable: dogechat_macOS
    test:
      config: Debug
      targets:
        - dogechatTests_macOS
    profile:
      config: Release
      executable: dogechat_macOS
    analyze:
      config: Debug
    archive:
      config: Release
